### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by giftig** [fgeller/kt#101]
Your latest release is from 2017 and has bugs which have since been fixed (e.g. #100). Can you provide a new release please?

**Comment by rdohms** [comment]
would love for this to happen, impossible to install via homebrew.

**Comment by prologic** [comment]
Yes please create a new binary release. You added the `admin` sub-command in da7df58a9cec1a57067d4cb0d8c9b87665a1bd53 but this is not available in the latest released binary.

**Comment by prologic** [comment]
In the meantime i've [forked this](https://github.com/prologic/kt) and new v12.1.1 binaries can be founed [here](https://github.com/prologic/kt/releases/tag/v12.1.1)

**Comment by robsonpeixoto** [comment]
https://github.com/birdayz/kaf is a good alternative
