### ISSUE TITLE
Latest release (v12.1.0) is 2.5 years old

### ISSUE THREAD

**Issue by navbruce** [fgeller/kt#111]
Is there any plan to cut a new release? If not, perhaps the README.md installation
instructions should be cut back to:

    go get -u github.com/fgeller/kt

... since 12.1.0 doesn't even support the TLS options in `master`.

**Comment by fgeller** [comment]
@navbruce thanks for the ping -- i've been offline for most of that time as a full-time dad, but started to resume my github projects yesterday. give me a few days and i'll cut a new release, thanks for being interested! closing the issue for now, feel free to continue/re-open the issue in case i missed something!
