### ISSUE TITLE
Can't use tk, after update macSO to Monterey

### ISSUE THREAD

**Issue by alXmas** [fgeller/kt#125]
### My environment:
macOS Monterey 12.0.1
kt version v13.0.0
### What I expect to happen?
```
➜  kt git:(master) ✗ ./kt -v
kt is a tool for Kafka.

Usage:

	kt command [arguments]
...
```
### What actually happened?
```
➜  ~ kt -v
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x132711e, 0x21)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0x7ff7bfeff460 sp=0x7ff7bfeff440 pc=0x102ae85
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:108 +0x83 fp=0x7ff7bfeff490 sp=0x7ff7bfeff460 pc=0x1028723
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:482 +0xa1 fp=0x7ff7bfeff4d0 sp=0x7ff7bfeff490 pc=0x102d831
runtime.rt0_go(0x7ff7bfeff508, 0x2, 0x7ff7bfeff508, 0x0, 0x1000000, 0x2, 0x7ff7bfeff798, 0x7ff7bfeff79b, 0x0, 0x7ff7bfeff79e, ...)
	/usr/local/go/src/runtime/asm_amd64.s:175 +0x1eb fp=0x7ff7bfeff4d8 sp=0x7ff7bfeff4d0 pc=0x1055d3b
```
### How resolve this problem ?
https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue

**Comment by alXmas** [comment]
I resolve this problem just update go version in `go.mod` to `go 1.16`. Can make the PR?

**Comment by fgeller** [comment]
hey! i updated go.mod but it'll take me a few days to cut a new release. but maybe you can try to build a new binary from master until then?

**Comment by fgeller** [comment]
finally got around to pushing out a release, hope that addresses this issue, please re-open in case the issue persists for you
