### ISSUE TITLE
Version string of v13.1.0 is still v13.0.0

### ISSUE THREAD

**Issue by darklore** [fgeller/kt#133]
Hello

Version string displayed by `kt -version` command is still v13.0.0

```
$ kt -version
kt version v13.0.0+ (5ecef5c @ 2022-01-22T22:08:52+01:00)
```

https://github.com/fgeller/kt/blob/master/main.go#L8 seems still v13.0.0

**Comment by fgeller** [comment]
hi @darklore - thanks for the feedback, forgot to update the string! i updated it on master, but will cut a new release in the coming days and then the version string will get updated again - if i don't forget it again :crossed_fingers: :wink:
