### ISSUE TITLE
Allow reading last X messages

### ISSUE THREAD

**Issue by echojc** [fgeller/kt#20]
Like `tail -nX`. Even nicer would be `tail -f -nX`, i.e., read _from_ the last X messages and keep going.

Not sure what the syntax should be . Usually you'd use negative numbers but that overlaps with your current usage of `-` for range. My inclination would be to change your range operator to something else because negative numbers for reverse offset feels _really_ nice, but yeah, not sure if you want to change that.

**Comment by nmaquet** [comment]
:+1: pretty please :D

**Comment by nmaquet** [comment]
Thanks ! :tada:
