### ISSUE TITLE
Consumer hangs when trying to consume old offsets on a 0.10 broker

### ISSUE THREAD

**Issue by lucianjon** [fgeller/kt#29]
When trying to consume from a topic using offsets older than a certain point the consumer will hang until you kill it. It appears to work fine using `offsetsNewest` or an absolute value above some point. When trying to consume a topic with 155 log entries and starting with an offset anywhere under roughly 30 would hang. Anything above that would work as normal.

This appears to only affect consuming against 0.10 clusters.

**Comment by fgeller** [comment]
i tried this against a kafka 10 broker (after upgrading sarama):

```
$ ./kt consume -brokers fg.lan -topic x -offsets all=150:155
{"partition":0,"offset":150,"key":null,"value":"hello"}
{"partition":0,"offset":151,"key":null,"value":"hello"}
{"partition":0,"offset":152,"key":null,"value":"hello"}
{"partition":0,"offset":153,"key":null,"value":"hello"}
{"partition":0,"offset":154,"key":null,"value":"hello"}
{"partition":0,"offset":155,"key":null,"value":"hello"}
$
```

is that what caused issues before?
the kt version above defaults to protocol v0.10.0.0 but you can specify it as well. e.g. to use v0.9.0.1:

```
$ ./kt consume -brokers fg.lan -topic x -version v0.9.0.1 -offsets all=150:155
```

could you upgrade kt and re-open if issue remains?
```
go get -u github.com/fgeller/kt
```
or via the [releases](../releases).
