### ISSUE TITLE
Failed to send message results in kt not responding

### ISSUE THREAD

**Issue by jackhopner** [fgeller/kt#33]
`Failed to send message, quitting. err=kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.
^C2016/10/13 09:38:55 Received interrupt - shutting down...`

When failing to produce a message, if you try kill kt (ctrl + c) it just hangs forever.

**Comment by jackhopner** [comment]
Also looks like you can't kill kt if it's in the middle of producing.

**Comment by fgeller** [comment]
@jackhopner That err message was removed in June, could you try running 
```
go get -u github.com/fgeller/kt
```
that would get you the latest (unreleased) or download the latest release from https://github.com/fgeller/kt/releases ?

**Comment by fgeller** [comment]
closing this for now - please re-open if you see it again @jackhopner
