### ISSUE TITLE
Avro / Schema Registry support

### ISSUE THREAD

**Issue by nmaquet** [fgeller/kt#40]
Avro + (optionally) Schema Registry support would be an awesome addition to kt for those of us who can't afford fat JSON payloads.

The Confluent Platform has two command-line tools `kafka-avro-console-producer` and `kafka-avro-console-consumer` that either take the schema directly on the command-line, and can also connect to Schema Registry. Similar functionality in `kt` would be really useful!

E.g.

```
$ ./bin/kafka-avro-console-producer \
         --broker-list localhost:9092 --topic test \
         --property value.schema='{"type":"record","name":"myrecord","fields":[{"name":"f1","type":"string"}]}'
```

**Comment by fgeller** [comment]
i played a bit with this - but would prefer to keep this out of kt. should be as easy to write another small utility that takes json input (possibly with base64 encoded binary data) and then encodes/decodes avro data that could be piped into kt.

**Comment by devaudio** [comment]
bah, easy if you are GOOD at jq.... if you suck it's quite a chore 😹
