### ISSUE TITLE
Panic when a message gets deleted (using a retention period) while consuming

### ISSUE THREAD

**Issue by utdemir** [fgeller/kt#59]
To reproduce: 

* Start consuming from a topic
* While consuming, do `bin/kafka-configs.sh --zookeeper dockerhost:2181 --alter --entity-type topics --add-config 'retention.ms=1000, cleanup.policy=delete'  --entity "thetopicname"`
* After a while, when messages get deleted, you'll get the below error.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1277f0f]

goroutine 73 [running]:
main.(*consumeCmd).partitionLoop(0xc4200a0210, 0xc420313d40, 0x147f200, 0xc420314080, 0x7, 0x7fffffffffffffff)
	/private/var/folders/qk/xbjs71jn3pg85_vzg1k2vgf40000gn/T/nix-build-kt-11.1.0.drv-0/go/src/github.com/fgeller/kt/consume.go:396 +0x32f
main.(*consumeCmd).consumePartition(0xc4200a0210, 0xc420313d40, 0xc400000007)
	/private/var/folders/qk/xbjs71jn3pg85_vzg1k2vgf40000gn/T/nix-build-kt-11.1.0.drv-0/go/src/github.com/fgeller/kt/consume.go:352 +0x51b
main.(*consumeCmd).consume.func1(0xc420305c10, 0xc4200a0210, 0xc420313d40, 0x7)
	/private/var/folders/qk/xbjs71jn3pg85_vzg1k2vgf40000gn/T/nix-build-kt-11.1.0.drv-0/go/src/github.com/fgeller/kt/consume.go:318 +0x63
created by main.(*consumeCmd).consume
	/private/var/folders/qk/xbjs71jn3pg85_vzg1k2vgf40000gn/T/nix-build-kt-11.1.0.drv-0/go/src/github.com/fgeller/kt/consume.go:318 +0xea
```

**Comment by fgeller** [comment]
hi @utdemir  - sorry, missed this one. i just tried to reproduce it with the following steps:

```
$ git checkout v11.1.0
$ ./kafka-topics.sh --create --topic zzz --partitions 1 --replication-factor 1 --zookeeper zookeeper:2181
```

then keep producing:

```
while true; do echo '{"key": "1", "value": "hans"}' | kt produce -topic zzz ; sleep 1 ; done
```

and consuming:

```
kt consume -topic zzz
```

and then change the config:

```
$ ./kafka-configs.sh --zookeeper zookeeper:2181 --alter --entity-type topics --add-config 'retention.ms=10, cleanup.policy=delete' --entity-name "zzz"
```

but i don't see the nil pointer dereference - am i missing a step?

reading the relevant lines - `v11.1.0` tried to access the contents of a message even if the chan was closed, so i'm guessing that's what you encountered. `master` doesn't have that ordering issue and i added a case to listen on the partition consumer's err chan. if you can reliably reproduce the issue, could you try master?

**Comment by fgeller** [comment]
hi @utdemir  - i'll close this optimistically for now - please feel free to re-open if you can reproduce it with master :)
