### ISSUE TITLE
Unable to run kt: command not found

### ISSUE THREAD

**Issue by mohigup** [fgeller/kt#60]
Hi,

I tried steps as provided in readme i.e.` go get -u github.com/fgeller/kt`.
However, I am unable to run the tool and seeing message **"bash: kt: command not found"** on typing kt in terminal (mac os)
Please help.

**Comment by fgeller** [comment]
Hi @mohigup,

please make sure that `$GOPATH/bin` is on your `$PATH`.
cf: https://golang.org/doc/code.html#GOPATH

Also be aware that `go get -u ...` pulls the latest version of kt, if you prefer a more stable and tested version, please download the latest release: https://github.com/fgeller/kt/releases/tag/v11.1.0

Closing for now, but feel free to continue the thread :)

**Comment by mohigup** [comment]
Thanks for the Reply. I will try again.
