### ISSUE TITLE
Not able to change the offset

### ISSUE THREAD

**Issue by chandradeepak** [fgeller/kt#61]
kt group -group enews -topic actor-news -partitions 0
found 1 groups
found 1 topics
failed to read partition offset for topic=actor-news partition=0 err=EOF

i am using kafka version  2.10-0.10.0.1.

i don't know why. can you please help me . 

In the kafka logs it shows this error 

ERROR Closing socket for 127.0.0.1:9092-127.0.0.1:59373 because of error (kafka.network.Processor)
kafka.network.InvalidRequestException: Error getting request for apiKey: 2 and apiVersion: 1
	at kafka.network.RequestChannel$Request.liftedTree2$1(RequestChannel.scala:95)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:87)
	at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:488)
	at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:483)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at kafka.network.Processor.processCompletedReceives(SocketServer.scala:483)
	at kafka.network.Processor.run(SocketServer.scala:413)

If i update my kafka to kafka_2.10-0.10.1.0 the command worked. but if i reset the consumer using 
kt group -group enews -topic actor-news -partitions 0 -reset 1 and then i start consumer it doesn't  starting sending me the data from offset 1.  can you please explain how to reset it .

**Comment by fgeller** [comment]
hi @chandradeepak, can you try to pass the version explicitly? e.g.:

```
kt group -group -enews -topic actor-news -partitions -version v0.10.0.1
```

or

```
kt group -group -enews -topic actor-news -partitions -reset 1 -version v0.10.0.1
```

if that doesn't work, can you please tell me which version of kt you're using?

**Comment by chandradeepak** [comment]
Thanks @fgeller , i was able to make the request using the version you provided but still the reset doesn't work.  when the consumer read some messages i set the offset to 1 . then i see this in consumer offset topic 
[enews,actor-news,0]::[OffsetMetadata[1,NO_METADATA],CommitTime 1501262669060,ExpirationTime 1501349069060]

now reset to 4. it will work 
[enews,actor-news,0]::[OffsetMetadata[4,NO_METADATA],CommitTime 1501262809879,ExpirationTime 1501349209879]

now reset to 1 . it will never work. 






kt group -group enews -topic actor-news -partitions 0 -reset 1 -version v0.10.0.1
found 1 groups
found 1 topics
{
  "name": "enews",
  "topic": "actor-news",
  "offsets": {
    "0": {
      "offset": 1,
      "lag": 5
    }
  }
}


kt group -group enews -topic actor-news -partitions 0 -version v0.10.0.1
found 1 groups
found 1 topics
{
  "name": "enews",
  "topic": "actor-news",
  "offsets": {
    "0": {
      "offset": 4,
      "lag": 2
    }
  }
}

**Comment by chandradeepak** [comment]
Found the problem 

in the code of offset_manager.go there is 

func (pom *partitionOffsetManager) MarkOffset(offset int64, metadata string) {
	pom.lock.Lock()
	defer pom.lock.Unlock()

	_//if offset > pom.offset {_
	pom.offset = offset
	pom.metadata = metadata
	pom.dirty = true
	_//}_
}


i had to comment the if part to make it work. then it reset the offset and working by really resetting the offset . do you think there is a reason why they wont reset to older offsets less than the pom.offset.

**Comment by fgeller** [comment]
nice! 

forgot to maintain that patch on master - updated it now. i'm not sure why upstream isn't allow resets to smaller offsets - i think it's a reasonable use case. here's the upstream issue: https://github.com/Shopify/sarama/issues/554

ok to close this issue?

**Comment by fgeller** [comment]
closing the issue for now - @chandradeepak feel free to re-open if you run into any more related issues

**Comment by chandradeepak** [comment]
@fgeller , thanks for letting me know about the issue opened in sarama. This issue is good to close now .  Thanks for the tool , it is cool.

**Comment by fgeller** [comment]
👍 glad it is of help!
