### ISSUE TITLE
kt topic requests for topics that don't exist don't log errors nor exit with code != 0

### ISSUE THREAD

**Issue by marianogappa** [fgeller/kt#66]

**Comment by fgeller** [comment]
ie indicate that there where no results via return code? (doesn't sound like an err to me)

**Comment by marianogappa** [comment]
Ah because it's a filter; not a specific topic.

**Comment by fgeller** [comment]
mh, i think changing the return code would make sense - that's what grep does from what i can tell. just think logging an error feels off

**Comment by marianogappa** [comment]
@fgeller kafka-topics' behaviour is consistent with kt.
