### ISSUE TITLE
Consuming null message value should be consistent with producing

### ISSUE THREAD

**Issue by vmaurin** [fgeller/kt#67]
In reference to issue #24 , while consuming null value message from Kafka, the output json should contains
```
"value": null
```
currently it is outputing
```
"value": ""
```
It could be convenient for doing a data backup or a data transfer between topics. A current workaround is to use jq tool to replace the empty string by null, but it only works if the topic is not supposed to contain empty string
Here the jq
```
jq -c '{partition:.partition,key:.key,value:(if (.value|length) > 0 then .value else null end)}'
```

**Comment by fgeller** [comment]
@vmaurin thanks for the feedback - i applied a quick fix that i need to clean up with a bit more time. keen to give it a test run? Just via the usual 
```
go get -u github.com/fgeller/kt
```

**Comment by vmaurin** [comment]
Thank you for the quick fix @fgeller 
So it is working in my use case, but I am not sure the fix is suitable for everybody. Kafka seems to behave differently on this 3 different scenarios (at least with jdk clients) : 
* when a message is produced with a null value, it is a deletion marker, used for example by log compaction
* when a message is produced with an empty byte array, it is not a deletion marker, just an empty message
* when a message is produced with a non empty byte array, it is a normal non empty message

The behavior I would expect from kt is : 
* having `"value":null` when it is a deletion marker
* having `"value":""` when it is an empty message
* having `"value":"xxxxx"` otherwise

**Comment by vmaurin** [comment]
I am not so familiar with go, but seems that 
```
if msg.Value == nil {
	m.Value = nil
} else {
	var str string
	switch cmd.encodeValue {
	case "hex":
		str = hex.EncodeToString(msg.Value)
	case "base64":
		str = base64.StdEncoding.EncodeToString(msg.Value)
	default:
		str = string(msg.Value)
	}
	m.Value = &str
}
```
do the trick. Previously it was probably empty due to the creation of the string v

**Comment by fgeller** [comment]
@vmaurin - yep, that was my misinterpretation. changed in the above commit. let me know what you think!

**Comment by vmaurin** [comment]
It sounds pretty good ! 
Thanks @fgeller
