### ISSUE TITLE
Run with docker

### ISSUE THREAD

**Issue by Paxa** [fgeller/kt#68]
I've build minimal docker image to run `kt` - https://hub.docker.com/r/evpavel/kt/

(could not find any info about docker images)

**Comment by fgeller** [comment]
Nice! Haven't had the use case myself, but thanks for sharing. Mind if I link to it from the readme?

**Comment by Paxa** [comment]
Sure!
I use it for checking groups and topics in kubernetes cluster, also resetting group offsets

**Comment by fgeller** [comment]
Cool - done! I'll close the issue optimistically, let me know if there's something else!
