### ISSUE TITLE
How to set group for consume?

### ISSUE THREAD

**Issue by Paxa** [fgeller/kt#69]
As I see `kt consume` works without group, so every time it will start from beginning

Is there a way to specify consumer group?

**Comment by fgeller** [comment]
Hi, not at the moment. The use cases we've had were mostly adhoc, so instead you can specify an offset to start from for each partition. e.g.

`kt consume -topic x -offsets all=10:20` would consume between offsets 10 and 20 (inclusive) on all partitions.

`kt consume -topic x -offsets 1=10:20,2=10:20` the same just for partitions 1 and 2.

And this is my most common use case:

`kt consume -topic x -offsets all=newest-10:` - ie consume the last 10 messages for each partition.

Hope that helps.

**Comment by Paxa** [comment]
Thanks 👍
