### ISSUE TITLE
Add JSON output format

### ISSUE THREAD

**Issue by echojc** [fgeller/kt#7]
It'd be cool if there's an option to use a JSON output format compatible with https://github.com/echojc/kp so that we can pipe output from `kt` into `kp` preserving partitioning and keys, useful for testing, debugging, and transferring data between (test) clusters.

**Comment by fgeller** [comment]
Tested this by piping messages from one topic to another:

```
$ ./kp --json test
{"partition":0,"key":"blubbs","message":"hellos"}
```

and

```
$ kt -json -topic test | ./kp --json test2
```

and

```
$ kt -topic test2 -offset 2:
Partition=0 Offset=2 Key=blubbs Message=hellos
```

Published this to https://github.com/fgeller/kt/releases/download/v1.1.0/kt-1.1.0-linux.xz

Let me know how you go :)
