### ISSUE TITLE
homebrew?

### ISSUE THREAD

**Issue by AlJohri** [fgeller/kt#75]
hi! sorry if this has been asked before, but would you consider also distributing via homebrew for macOS? thanks!

**Comment by fgeller** [comment]
hi @AlJohri  - sorry for the delay, and i don't think someone else has asked for this. I don't have a mac anymore, so would have to read up on how homebrew distribution works nowadays, or are you interested in contributing this?

**Comment by fgeller** [comment]
@AlJohri it's been a while, but I added a formula and tested it as well:

```sh
$ brew tap fgeller/tap
$ brew install kt
```

closing this issue for now, let me know if you run into any issues
