### ISSUE TITLE
Support for "resume" offset?

### ISSUE THREAD

**Issue by gengel** [fgeller/kt#78]
Since kt sets a consumer group id, it should be possible to simply start reading from a given TopicPartition based on the offset where it stopped reading the last time it was run for that username? (Assuming that kt commits offsets as it reads)

Something like `kt consume -offsets all=resume` would be handy.

**Comment by fgeller** [comment]
@gengel sorry for the delay - but i just pushed a version that supports a `resume` keyword, similar to `newest` and `oldest`. use `go get -u github.com/fgeller/kt` if you want to test it now, or let me know - it might be a couple of days before i package a release.

**Comment by gengel** [comment]
Woohoo, this is wonderful news!
