### ISSUE TITLE
Cannot consume from kafka broker 2.0.0

### ISSUE THREAD

**Issue by vmaurin** [fgeller/kt#83]
Hello
I have tried to consume messages produced in a broker 2.0.0, with console producer same version with kt and it fails
Enabling the verbose mode, I got this output
```
2018/09/03 16:14:42 Connected to broker at xxxx:9092 (registered as #0)
2018/09/03 16:14:42 consumer/broker/0 added subscription to test/2
2018/09/03 16:14:42 consumer/broker/0 disconnecting due to error processing FetchRequest: kafka: error decoding packet: CRC didn't match
2018/09/03 16:14:42 Closed connection to broker xxxx:9092
2018/09/03 16:14:42 kafka: error while consuming test/2: kafka: error decoding packet: CRC didn't match
```
Something seems incompatible with the protocol

**Comment by fgeller** [comment]
@vmaurin hey there - sorry that it took so long, but with @ebati 's help, we updated sarama on master and at least on travis the system tests pass against kafka 2.0 - would you mind giving it a go and report issues you run into?

**Comment by fgeller** [comment]
closing this for now, all system tests run against kafka 2.0 for a while now, and kt's defaults to expect kafka 2.0 as well. please re-open or create another issue if you run into any problems. thanks for reporting
