### ISSUE TITLE
Timestamps are not added when producing

### ISSUE THREAD

**Issue by fuyar** [fgeller/kt#95]
Hello,

When producing with kt, record timestamps (available since Kafka 0.10) are not specified.
Here's an example with what kafkacat is producing.

```echo '{"key":"test","value":null}' | kt produce -brokers localhost -topic test_timestamp
{"partition": 0,"offset": 0, "timestamp": -1, "key": test, "value": NULL}

echo 'test:' | kafkacat -P -b dbpoc-03 -t test_timestamp -K: -Z -p -1
{"partition": 4,"offset": 0, "timestamp": 1544028030676, "key": test, "value": NULL}
```

Also kt is not using the default partitioner (the one from Kafka) ?

**Comment by fgeller** [comment]
hey @fuyar got around to adding the timestamp bit today - let me know if you run into any issues - and added a new issue to check again on a default partitioner implementation in go.

closing this optimistically, feel free to re-open!
